docs: added for core-sdk-golang
immutable/imx-docs pull request #100
Opened 2022-08-18 02:42 UTC by zatlite

## Description

Documentation for imx-core-sdk-golang

## Resolved issues
Jira: [DX-1087]

### Before submitting the PR, please consider the following:
- [ ] It's beneficial if your pull request references an issue used to discuss the pull request ahead of time. If you haven't previously created an issue, please create one and discuss your contribution with the maintainers.
- [ ] Prefix your PR title with `feat: `, `fix: `, `chore: `, `docs:`, or `refactor:`.
- [ ] The description should clearly illustrate what problems the pull request solves.
- [ ] Ensure that the commit messages follow our guidelines.
- [ ] Resolve merge conflicts (if any).
- [ ] Make sure that the current branch is up to date with the `main` branch.

### For internal Immutable developers:
- [ ] If you are adding or updating a documentation page, please also add or update the team ownership of that page (follow [this guide](https://immutable.atlassian.net/wiki/spaces/PPS/pages/1947927045/Docs+ownership+registry#What-to-do-when-adding%2Fupdating-documentation-pages%3F)).
- [ ] If you are adding or updating documentation for an SDK, please make sure that you meet the requirements in [this doc](https://immutable.atlassian.net/wiki/spaces/PPS/pages/1916994017/SDK+documentation+guide).
- [ ] Please obtain PR approval from all of the following:
    - Your tech lead (Fallback: Team lead or engineering manager)
    - Your product manager (Fallback: Group PM)
    - Another software engineer on your team

2022-08-18 06:29 UTC, matthewmuscat approved these changes
LGTM

2022-08-18 23:27 UTC, sprngbk requested changes
Great work! Just some comments/suggestions - also since these are taken from the Golang README and the README is supposed to be the source of truth, they need to be updated there.

2022-08-18 23:27 UTC, sprngbk commented on docs/sdk-docs/core-sdk-golang/additional-info.md
> +Immutable X is built as a ZK-rollup in partnership with StarkWare. We chose the ZK-rollups because it is the only solution capable of scale without compromise. This means whenever you mint or trade a
```suggestion
Immutable X is built as a ZK-rollup in partnership with StarkWare. We chose ZK-rollups because it is the only L2 scaling solution that has the same security guarantees as layer 1 Ethereum. The upshot of this is that you can mint or trade NFTs on Immutable X with zero gas costs whilst not compromising on security. This mechanism is the first true “layer 2” for NFTs on Ethereum.
```

2022-08-18 23:27 UTC, sprngbk commented on docs/sdk-docs/core-sdk-golang/additional-info.md
> +[See all smart contract available in the Core SDK](#smart-contract-autogeneration)
```suggestion
[See all smart contracts available in the Core SDK](#smart-contract-autogeneration)
```

2022-08-18 23:27 UTC, sprngbk commented on docs/sdk-docs/core-sdk-golang/additional-info.md
> +The Immutable solidity contracts can be found under `contracts` folder. Contract bindings in golang is generated using [abigen](https://geth.ethereum.org/docs/dapp/native-bindings#abigen-go-binding-g
```suggestion
The Immutable Solidity contracts can be found in the `contracts` folder. Contract bindings in Golang are generated using [abigen](https://geth.ethereum.org/docs/dapp/native-bindings#abigen-go-binding-generator).
```

2022-08-19 01:20 UTC, zatlite commented on sidebars/sidebars-core-sdk-golang.js
> +          label: 'Api Client Reference',
[e881d14](https://github.com/immutable/imx-docs/pull/100/commits/e881d14908ec8120a87217ad13588532acefeb56)

2022-08-30 01:25 UTC, sprngbk approved these changes
LGTM!

2022-08-30 01:25 UTC, sprngbk commented on sidebars/sidebars-core-sdk-golang.js
> +          label: 'Api client reference',
```suggestion
          label: 'API client reference',
```

2022-08-30 06:40 UTC, merged