Wallet SDK UI/UX Guide
immutable/imx-docs pull request #105
Opened 2022-08-18 06:15 UTC by lzanchin-immutable

The guide with the recommended UI/UX expected when partners use the Wallet SDK.

## Description

The guidelines we will recommend to partners who adopt the Wallet-SDK-web in conjunction with the Core-SDK.

2022-08-19 02:26 UTC, sprngbk requested changes
Thanks Leandro, just left some comments and suggestions.

Just a couple of things to note:
* I removed references to "partners" and replaced with "application" where necessary because I think it's a more generic term and this guide will also be used by our self-serve users
* I removed "Partner must have" phrases because that is implied as it is in the "Requirements" column. I think it's clear that these are mandatory when we highlight the practices that are "not mandatory, but useful to include..."
* Can we please use **sentence casing** throughout this guide according to our style manual [here](https://immutable.atlassian.net/wiki/spaces/PPS/pages/1937278619/Style+manual#id-%E2%9C%92%EF%B8%8F%F0%9F%93%84Stylemanual-Capitalizethefirstwordinasentenceandinheadings)?

2022-08-19 02:26 UTC, sprngbk commented on docs/main/guides/wallet-sdk-ui-guide.md
> +                </ul>
```suggestion
                <ul>
                    <li>Display the purchase price</li>
                    <li>Display the purchase currency</li>
                    <li>Provide breakdown of any maker and taker fees that apply</li>
                </ul>
                Not mandatory, but useful to have:
                <ul>
                    <li>User feedback that purchase was successful</li>
                    <li>Send users to an "add funds" flow if they have insufficient funds</li>
                </ul>    
```

2022-08-19 02:26 UTC, sprngbk commented on docs/main/guides/wallet-sdk-ui-guide.md
> +- Payment flow entry points (Deposit from L1, Onramp with Moonpay, Pay with CC through Moonpay).
Where are these points meant to sit?

2022-08-19 02:26 UTC, sprngbk commented on docs/main/guides/wallet-sdk-ui-guide.md
> +                </ul>
```suggestion
                <ul>
                    <li>Provide an "add funds" flow</li>
                </ul>
```

2022-08-19 02:26 UTC, sprngbk commented on docs/main/guides/wallet-sdk-ui-guide.md
> +                </ul>
```suggestion
                <ul>
                    <li>Provide a field for the user to input the currency type</li>
                    <li>Provide a field for the user to input the amount they want to deposit</li>
                </ul>
                Not mandatory, but useful to have:
                <ul>
                    <li>Icons representing different currency types</li>
                    <li>Available L1 balance to be deposited</li>
                    <li> Feedback when a deposit is successful</li>
                </ul>    
```

2022-08-19 02:26 UTC, sprngbk commented on docs/main/guides/wallet-sdk-ui-guide.md
> +# L2 to L1 Withdraw
```suggestion
# L2 to L1 withdrawal
```

2022-08-19 02:26 UTC, sprngbk commented on docs/main/guides/wallet-sdk-ui-guide.md
> +# Fiat On-Ramp [ workflow to be added ]
Does this mean that the workflow does not yet exist in the Wallet SDK?

2022-08-19 02:26 UTC, sprngbk commented on docs/main/guides/wallet-sdk-ui-guide.md
> +            Moonpay widget will take care of the rest
```suggestion
            <ul>
                <li>Trigger the onramp flow</li>
            </ul>
            The Moonpay widget will take care of the rest.
```

2022-08-19 02:26 UTC, sprngbk commented on docs/main/guides/wallet-sdk-ui-guide.md
> +            </ul>
```suggestion
            <ul>
                <li>Trigger the offramp flow</li>
            </ul>
            The Moonpay widget will take care of the rest.

            Not mandatory, but useful to have:
            <ul>
                <li>A note informing the user that the Moonpay offramp is only available to users in the US, UK, and EU.</li>
            </ul>
```

2022-08-19 02:26 UTC, sprngbk commented on docs/main/guides/wallet-sdk-ui-guide.md
> +            </ul>
```suggestion
            <ul>
                <li>Provide user feedback about specific errors (full list of errors can be found <a href="https://docs.x.immutable.com/docs/link-errors/">here</a>)</li></li>
            </ul>
            Not mandatory, but useful to have:
            <ul>
                <li>Link to Immutable support page</li>
            </ul>
```

2022-08-19 02:26 UTC, sprngbk commented on docs/main/guides/wallet-sdk-ui-guide.md
> +            </ul>
```suggestion
            <ul>
                <li>Provide users with the ability to view their transaction history</li>
                <li>For each transaction, they must provide information about the transaction ID, asset details, type of transaction and the costs involved.</li>
            </ul>
```

2022-08-21 22:22 UTC, lzanchin-immutable commented on docs/main/guides/wallet-sdk-ui-guide.md
> +                    <li>If having both Metamask and Gamestop as wallet options, explain somehow that having both plugins at the same time can cause issues to the wallet connection</li>
I will include a link to the support page which have more details. (https://support.immutable.com/hc/en-us/articles/5160531224079-Managing-multiple-wallet-extensions-for-Immutable)

2022-08-21 22:23 UTC, lzanchin-immutable commented on docs/main/guides/wallet-sdk-ui-guide.md
> +# Fiat On-Ramp [ workflow to be added ]
Correct

2022-08-22 04:02 UTC, sprngbk approved these changes
Looks great, thanks Leandro!

2022-08-22 04:20 UTC, merged