docs: WT-804/WT-807 Core SDK and Wallet SDK doc sync-ups with their README versions
immutable/imx-docs pull request #115
Opened 2022-09-05 21:28 UTC by RenatoChitolina

## Description

Synchronizing docs with their related repository READMEs.

## Resolved issues
Jira:
https://immutable.atlassian.net/browse/WT-804
https://immutable.atlassian.net/browse/WT-807

### Before submitting the PR, please consider the following:
- [X] It's beneficial if your pull request references an issue used to discuss the pull request ahead of time. If you haven't previously created an issue, please create one and discuss your contribution with the maintainers.
- [X] Prefix your PR title with `feat: `, `fix: `, `chore: `, `docs:`, or `refactor:`.
- [X] The description should clearly illustrate what problems the pull request solves.
- [X] Ensure that the commit messages follow our guidelines.
- [X] Resolve merge conflicts (if any).
- [X] Make sure that the current branch is up to date with the `main` branch.

### For internal Immutable developers:
- [X] If you are adding or updating a documentation page, please also add or update the team ownership of that page (follow [this guide](https://immutable.atlassian.net/wiki/spaces/PPS/pages/1947927045/Docs+ownership+registry#What-to-do-when-adding%2Fupdating-documentation-pages%3F)).
- [X] If you are adding or updating documentation for an SDK, please make sure that you meet the requirements in [this doc](https://immutable.atlassian.net/wiki/spaces/PPS/pages/1916994017/SDK+documentation+guide).
- [X] Please obtain PR approval from all of the following:
    - Your tech lead (Fallback: Team lead or engineering manager)
    - Your product manager (Fallback: Group PM)
    - Another software engineer on your team

2022-09-05 23:20 UTC, ABashkirtseva approved these changes

2022-09-06 00:17 UTC, sprngbk requested changes
Just some minor suggestions but otherwise, looks good! 👍

2022-09-06 00:17 UTC, sprngbk commented on docs/sdk-docs/core-sdk-ts/quickstart.md
> +A configuration object is required to be passed into Core SDK requests. This can be obtained by using the `getConfig` function available within the Core SDK. You are required to provide the correct c
```suggestion
A configuration object is required to be passed into Core SDK requests. This can be obtained by using the `getConfig` function available within the Core SDK. You are required to provide the correct contract addresses, Chain ID, and API base path of the network you wish to use. The Immutable X platform currently supports `ropsten` for testing and `mainnet` for production.
```

2022-09-06 00:17 UTC, sprngbk commented on docs/sdk-docs/core-sdk-ts/quickstart.md
> +// Setup a provider and a signer
```suggestion
// Set up a provider and a signer
```

2022-09-06 01:01 UTC, sprngbk approved these changes

2022-09-06 02:02 UTC, merged