feat: Add metadata refresh docs
immutable/imx-docs pull request #120
Opened 2022-09-12 02:39 UTC by allan-almeida

## Description

Add docs for metadata refresh feature: https://immutable.atlassian.net/wiki/spaces/IGG/pages/1957006096/GMS-95+Docs+for+metadata+refresh

## Resolved issues
Jira:

### Before submitting the PR, please consider the following:
- [x] It's beneficial if your pull request references an issue used to discuss the pull request ahead of time. If you haven't previously created an issue, please create one and discuss your contribution with the maintainers.
- [x] Prefix your PR title with `feat: `, `fix: `, `chore: `, `docs:`, or `refactor:`.
- [x] The description should clearly illustrate what problems the pull request solves.
- [x] Ensure that the commit messages follow our guidelines.
- [ ] Resolve merge conflicts (if any).
- [ ] Make sure that the current branch is up to date with the `main` branch.

### For internal Immutable developers:
- [ ] If you are adding or updating a documentation page, please also add or update the team ownership of that page (follow [this guide](https://immutable.atlassian.net/wiki/spaces/PPS/pages/1947927045/Docs+ownership+registry#What-to-do-when-adding%2Fupdating-documentation-pages%3F)).
- [ ] If you are adding or updating documentation for an SDK, please make sure that you meet the requirements in [this doc](https://immutable.atlassian.net/wiki/spaces/PPS/pages/1916994017/SDK+documentation+guide).
- [ ] Please obtain PR approval from all of the following:
    - Your tech lead (Fallback: Team lead or engineering manager)
    - Your product manager (Fallback: Group PM)
    - Another software engineer on your team

2022-09-12 02:52 UTC, allan-almeida commented on docs/main/guides/asset-management/asset-metadata-refreshes.md
> +<!-- INSERT_LINK - View the OpenAPI specification for requesting a metadata refresh -->
Once the metadata refresh service open api spec is merged with https://api.ropsten.x.immutable.com/openapi-docs i will enable these links

2022-09-12 03:06 UTC, ckailash requested changes

2022-09-12 03:06 UTC, ckailash commented on docs/main/guides/asset-management/asset-metadata-refreshes.md
> +GET BASE_URL/v1/metadata-refreshes/:refresh_id
Do we need the BASE_URL here? I think we could just say `/v1/metadata-refreshes` to be cleaner.

2022-09-12 03:06 UTC, ckailash commented on docs/main/guides/asset-management/asset-metadata-refreshes.md
> +POST BASE_URL/v1/metadata-refreshes
Could remove `BASE_URL`

2022-09-12 03:06 UTC, ckailash commented on docs/main/guides/asset-management/asset-metadata-refreshes.md
> +GET BASE_URL/v1/metadata-refreshes/:refresh_id/errors
Remove `BASE_URL`

2022-09-12 03:06 UTC, ckailash commented on docs/main/guides/asset-management/asset-metadata-refreshes.md
> +<table>
Can we have tables embedded without the file extension being `.mdx`? Please double check

2022-09-12 03:06 UTC, ckailash commented on docs/main/guides/asset-management/asset-metadata-refreshes.md
> +GET BASE_URL/v1/metadata-refreshes
Remove `BASE_URL`

2022-09-12 03:06 UTC, ckailash commented on docs/main/guides/asset-management/asset-metadata-refreshes.md
> +GET BASE_URL/v1/metadata-refreshes?collection_address=COLLECTION_ADDRESS
Remove `BASE_URL`

2022-09-12 03:19 UTC, allan-almeida commented on docs/main/guides/asset-management/asset-metadata-refreshes.md
> +<table>
Docusaurus can do html in `.md`: https://docusaurus.io/docs/markdown-features#details. I think for any JSX we would need an mdx file.

Also checked preview and looks fine: https://deploy-preview-120--imx-docs-prod.netlify.app/docs/asset-metadata-refreshes#viewing-metadata-refresh-errors

2022-09-12 03:19 UTC, allan-almeida commented on docs/main/guides/asset-management/asset-metadata-refreshes.md
> +GET BASE_URL/v1/metadata-refreshes/:refresh_id
agreed, removed

2022-09-12 03:20 UTC, allan-almeida commented on docs/main/guides/asset-management/asset-metadata-refreshes.md
> +POST BASE_URL/v1/metadata-refreshes
removed

2022-09-12 03:20 UTC, allan-almeida commented on docs/main/guides/asset-management/asset-metadata-refreshes.md
> +GET BASE_URL/v1/metadata-refreshes/:refresh_id/errors
removed

2022-09-12 03:20 UTC, allan-almeida commented on docs/main/guides/asset-management/asset-metadata-refreshes.md
> +GET BASE_URL/v1/metadata-refreshes
removed

2022-09-12 03:20 UTC, allan-almeida commented on docs/main/guides/asset-management/asset-metadata-refreshes.md
> +GET BASE_URL/v1/metadata-refreshes?collection_address=COLLECTION_ADDRESS
removed

2022-09-12 05:58 UTC, sprngbk requested changes
Thanks @allan-almeida! Just a couple of comments/suggestions.

2022-09-12 05:58 UTC, sprngbk commented on docs/main/guides/asset-management/asset-metadata-refreshes.md
> +- gameplay mechanics - orchestrate updates to support core gameplay mechanics like levelling up a character, crafting or merging
Can we capitalize the first word of each dot point?

2022-09-12 05:58 UTC, sprngbk commented on docs/main/guides/asset-management/asset-metadata-refreshes.md
> +The expected maximum time (estimated) to complete a refresh is roughly 48 hours.
```suggestion
The expected maximum time (estimate) to complete a refresh is approximately 48 hours.
```

2022-09-12 05:58 UTC, sprngbk commented on docs/main/guides/asset-management/asset-metadata-refreshes.md
> +- `x-imx-eth-address` - the eth address of the project owner making the request
```suggestion
- `x-imx-eth-address` - the Ethereum address of the project owner making the request
```

2022-09-12 05:58 UTC, sprngbk commented on docs/main/guides/asset-management/asset-metadata-refreshes.md
> +The error_code field describes why the metadata could not be updated.
Can we put this in list form?

2022-09-12 05:58 UTC, sprngbk commented on docs/main/guides/asset-management/asset-metadata-refreshes.md
> +<table>
I assume this is required to have the `code` blocks?

2022-09-12 05:58 UTC, sprngbk commented on docs/main/guides/asset-management/asset-metadata-refreshes.md
> +## API
Do you think we should have a section for the main errors that can be returned?

2022-09-12 22:51 UTC, allan-almeida commented on docs/main/guides/asset-management/asset-metadata-refreshes.md
> +<!-- INSERT_LINK - View the OpenAPI specification for requesting a metadata refresh -->
[This pr](https://github.com/immutable/imx-engine/pull/3150) needs to be pushed out before I can uncomment these links

2022-09-12 22:53 UTC, allan-almeida commented on docs/main/guides/asset-management/asset-metadata-refreshes.md
> +<table>
yep its the html for this table:
<img width="985" alt="Screen Shot 2022-09-13 at 8 52 49 am" src="https://user-images.githubusercontent.com/24609799/189772185-825c4a8a-4c27-42b5-baf8-d37717f86ed8.png">

2022-09-12 23:00 UTC, allan-almeida commented on docs/main/guides/asset-management/asset-metadata-refreshes.md
> +- gameplay mechanics - orchestrate updates to support core gameplay mechanics like levelling up a character, crafting or merging
Yep, now updated

2022-09-12 23:06 UTC, allan-almeida commented on docs/main/guides/asset-management/asset-metadata-refreshes.md
> +The error_code field describes why the metadata could not be updated.
yep, updated

2022-09-12 23:08 UTC, allan-almeida commented on docs/main/guides/asset-management/asset-metadata-refreshes.md
> +## API
This would be now under the section `Error codes`, would that be ok?

2022-09-13 00:51 UTC, allan-almeida commented on docs/main/guides/asset-management/asset-metadata-refreshes.md
> +<!-- INSERT_LINK - View the OpenAPI specification for requesting a metadata refresh -->
links now added to updated api reference pages

2022-09-16 05:16 UTC, sprngbk approved these changes

2022-09-18 23:18 UTC, merged