PT-162: docs: Add LayerSwap doc
immutable/imx-docs pull request #165
Opened 2022-11-03 03:01 UTC by ABashkirtseva

## Description

Describe your pull request here.

## Resolved issues
Jira:

### Before submitting the PR, please consider the following:
- [ ] It's beneficial if your pull request references an issue used to discuss the pull request ahead of time. If you haven't previously created an issue, please create one and discuss your contribution with the maintainers.
- [ ] Prefix your PR title with `feat: `, `fix: `, `chore: `, `docs:`, or `refactor:`.
- [ ] The description should clearly illustrate what problems the pull request solves.
- [ ] Ensure that the commit messages follow our guidelines.
- [ ] Resolve merge conflicts (if any).
- [ ] Make sure that the current branch is up to date with the `main` branch.

### For internal Immutable developers:
- [ ] If you are adding or updating a documentation page, please also add or update the team ownership of that page (follow [this guide](https://immutable.atlassian.net/wiki/spaces/PPS/pages/1947927045/Docs+ownership+registry#What-to-do-when-adding%2Fupdating-documentation-pages%3F)).
- [ ] If you are adding or updating documentation for an SDK, please make sure that you meet the requirements in [this doc](https://immutable.atlassian.net/wiki/spaces/PPS/pages/1916994017/SDK+documentation+guide).
- [ ] Please obtain PR approval from all of the following:
    - Your tech lead (Fallback: Team lead or engineering manager)
    - Your product manager (Fallback: Group PM)
    - Another software engineer on your team

2022-11-07 06:46 UTC, deepti-imx submitted a review, later dismissed

2022-12-06 01:04 UTC, sprngbk reviewed
Just an initial note - if you remove or update a docs page or URL, note the following:
* If this page has existed for a while, there may be external links to this doc. Please add a redirect ([example](https://github.com/immutable/imx-docs/blob/main/src/pages/docs/getting-started-guide.tsx))
* Make sure all internal links to this page are also updated

2022-12-06 01:12 UTC, sprngbk reviewed
In terms of style and formatting:
* `Immutable X` should be `ImmutableX` (see [this branding guide](https://immutable.atlassian.net/wiki/spaces/BRAND/pages/1916633841/Immutable+X))
* Follow [this guide](https://immutable.atlassian.net/wiki/spaces/PPS/pages/1978630151/Best+practices+for+guides+and+tutorials+in+ImmutableX+docs) for how to structure this page - also, look at our [existing docs](https://docs.x.immutable.com/docs/how-to-create-orders) for an example of how steps and code samples should be structured
* Can we structure the introductory information better? Create more coherent section groupings, for example, there are a lot of admonitions of varying alert levels, can we group them into a section (like "Pre-requisites" or "Things to know")?
<img width="903" alt="image" src="https://user-images.githubusercontent.com/96668470/205781912-e57fc371-855e-4725-9290-4b3290384953.png">

2022-12-06 06:20 UTC, sprngbk commented
Some more general suggestions:
* Put both the guides into one doc called `Crypto on and off-ramps`
* Link.onramp and offramp should be sequential in this list?
<img width="221" alt="image" src="https://user-images.githubusercontent.com/96668470/205836420-7b11c9b1-ec4f-4f75-ba31-62a3fbe7912b.png">

2022-12-06 22:01 UTC, sprngbk requested changes
Thanks for this! Looking good mostly, just some comments.

Also some general notes:
* Combine the on and off-ramp docs into one article, call it "Crypto on and off-ramps"
* Choose either "on-ramp"/"off-ramp" or "onramp"/"offramp" and use it consistently throughout the docs

2022-12-06 22:01 UTC, sprngbk commented on docs/main/guides/basic-guides/off-ramp-transfer/index.md
> +slug: "/how-to-enable-off-ramp"
Put both on and off-ramp guides into one doc.

```suggestion
slug: "/how-to-enable-crypto-on-off-ramps"
```

2022-12-07 02:25 UTC, deepti-imx commented on docs/main/guides/advanced-guides/nft-primary-sale-card-checkout/nft-checkout-primary-core-sdk.md
>  Upon failure, the transaction status will be updated to `failed`.
This note mentions different states of a single property on response object and how to keep checking the status until it has reached final stage.
Instead of note, I can keep it with the `verify the status` step to make it clear.

2022-12-07 04:50 UTC, sprngbk requested changes
Looking great! Just a couple of things:
* For both guides (on and off-ramps), have separate guides for both LayerSwap and Moonpay. We can distinguish them using the Tabs we use for the different SDKs:
<img width="900" alt="image" src="https://user-images.githubusercontent.com/96668470/206091298-2c008497-242f-4d92-9e7e-f520e20ad411.png">

2022-12-07 04:50 UTC, sprngbk commented on docs/main/guides/basic-guides/off-ramp-transfer/index.md
> +With Moonpay as the provider, the end-user will be asked to provide credit card details.
We should explain what on and off-ramps are, and make clear the difference between LayerSwap and Moonpay.

```suggestion
Typically, getting crypto onto ImmutableX Layer 2 wallets is a multi-step process. A common flow is users obtaining crypto on L1 (such as by purchasing it on an exchange like Coinbase), transfer it from the exchange to an L1 wallet that they own, then deposit it from the L1 wallet to their ImmutableX L2 wallet.

However, ImmutableX allow you to integrate with on and off-ramp providers in order to get crypto into L2 wallets in a single step:
| Provider | How does it work? | Fees | Min. purchase / deposit | Restrictions |
| --- | --- | --- | --- | --- |
| Moonpay | Users can buy crypto with a card payment and it is immediately transferred to their L2 wallet | [Moonpay transaction fee](https://support.moonpay.com/hc/en-gb/articles/360011930117-What-fees-do-you-charge-) | $20USD | Only available in EU, UK, and select US states. Please refer to [Moonpay’s help desk](https://support.moonpay.com/hc/en-gb/articles/4406268234641-What-countries-are-supported-to-sell-crypto-with-MoonPay-) for more information. |
| LayerSwap | Users can transfer crypto they own in a centralised exchange account (ie. Coinbase) directly to their L2 wallet | [Layerswap exchange fees](https://docs.layerswap.io/user-docs/using-layerswap/fees) | 0.025ETH | |
```

2022-12-07 04:50 UTC, sprngbk commented on docs/main/guides/basic-guides/off-ramp-transfer/index.md
> +### 2. Create the off-ramp exchange request
Remove "exchange" as Moonpay isn't an exchange

```suggestion
### 2. Create the off-ramp request
```

2022-12-07 04:50 UTC, sprngbk commented on docs/main/guides/basic-guides/off-ramp-transfer/index.md
> +### 2. Create the off-ramp exchange request
Provide examples of both Moonpay and LayerSwap requests

2022-12-07 04:50 UTC, sprngbk commented on docs/main/guides/basic-guides/on-ramp-transfer/index.md
> +:::
This can be removed if the table proposed above is added

2022-12-07 04:50 UTC, sprngbk commented on docs/main/guides/basic-guides/off-ramp-transfer/index.md
> +:::
This can be removed if the table proposed above is added

2022-12-08 05:36 UTC, sprngbk approved these changes

2022-12-08 23:16 UTC, merged