feat: include ImmutableX Wallet SDK iOS docs
immutable/imx-docs pull request #166
Opened 2022-11-04 01:02 UTC by CassiusPacheco

Include the first version of the ImmutableX Wallet SDK iOS docs v0.1.0

Opening a PR without the code docs so review is easier to be done. Please help me find out if anything is missing.

2022-11-04 02:57 UTC, CassiusPacheco commented
I've tested it in the following links:
https://deploy-preview-166--imx-docs-prod.netlify.app/docs/how-to-generate-signers/
https://deploy-preview-166--imx-docs-prod.netlify.app/sdk-docs/wallet-sdk-ios/overview
https://deploy-preview-166--imx-docs-prod.netlify.app/docs/sdks

let me know if I missed something!

2022-11-06 22:55 UTC, CassiusPacheco commented
@sprngbk @CodeSchwert when you have some time, can you please have a look at this, since it's a new entry in the docs? Thanks

2022-11-06 23:48 UTC, sprngbk requested changes

2022-11-06 23:48 UTC, sprngbk commented on docs/main/guides/basic-guides/generate-signers/index.md
> +If you want to use your own bridge server instead of the default provide it via bridgeServerUrl when connecting. For more info on how WalletConnect and the bridge works [see here](https://docs.wallet
This link (https://docs.walletconnect.com/tech-spec) doesn't work

2022-11-06 23:48 UTC, sprngbk commented on docs/main/guides/basic-guides/generate-signers/index.md
> +      <td><a href='https://github.com/immutable/imx-wallet-sdk-ios/'>Wallet SDK iOS</a></td>
I think this link should go to the SDK reference on the docs site instead of the Github repo... (However, we do need to provide a Github repo link in the sidebar as well, I'll add this to this PR)
```suggestion
      <td><a href='/docs/sdk-docs/wallet-sdk-ios/overview'>Wallet SDK iOS</a></td>
```

2022-11-07 00:53 UTC, CassiusPacheco commented on docs/main/guides/basic-guides/generate-signers/index.md
> +If you want to use your own bridge server instead of the default provide it via bridgeServerUrl when connecting. For more info on how WalletConnect and the bridge works [see here](https://docs.wallet
fixed it for ios and android

2022-11-07 00:53 UTC, CassiusPacheco commented on docs/main/guides/basic-guides/generate-signers/index.md
> +      <td><a href='https://github.com/immutable/imx-wallet-sdk-ios/'>Wallet SDK iOS</a></td>
fixed it, thanks

2022-11-07 01:04 UTC, sprngbk approved these changes
LGTM!

2022-11-07 02:00 UTC, sprngbk approved these changes

2022-11-07 02:00 UTC, merged