updated nft-checkout-primary-with-moonpay
immutable/imx-docs pull request #180
Opened 2022-11-21 16:44 UTC by jessemillman

## Description

Describe your pull request here.

## Resolved issues
Jira:

### Before submitting the PR, please consider the following:
- [ ] It's beneficial if your pull request references an issue used to discuss the pull request ahead of time. If you haven't previously created an issue, please create one and discuss your contribution with the maintainers.
- [ ] Prefix your PR title with `feat: `, `fix: `, `chore: `, `docs:`, or `refactor:`.
- [ ] The description should clearly illustrate what problems the pull request solves.
- [ ] Ensure that the commit messages follow our guidelines.
- [ ] Resolve merge conflicts (if any).
- [ ] Make sure that the current branch is up to date with the `main` branch.

### For internal Immutable developers:
- [ ] If you are adding or updating a documentation page, please also add or update the team ownership of that page (follow [this guide](https://immutable.atlassian.net/wiki/spaces/PPS/pages/1947927045/Docs+ownership+registry#What-to-do-when-adding%2Fupdating-documentation-pages%3F)).
- [ ] If you are adding or updating documentation for an SDK, please make sure that you meet the requirements in [this doc](https://immutable.atlassian.net/wiki/spaces/PPS/pages/1916994017/SDK+documentation+guide).
- [ ] Please obtain PR approval from all of the following:
    - Your tech lead (Fallback: Team lead or engineering manager)
    - Your product manager (Fallback: Group PM)
    - Another software engineer on your team

2022-11-24 06:03 UTC, deepti-imx approved these changes

2022-11-25 03:36 UTC, sprngbk commented on docs/main/tutorials/nft-checkout-primary-with-moonpay.md
>  title: "NFT Checkout Primary Moonpay"
Can we change this name - it's not very descriptive:
* Let's remove "primary" - it's not a useful term
* Should there be some reference to the fact that this is NFT checkout using a CC/fiat? Perhaps something like: "Setting up fiat/CC NFT checkout with Moonpay"?

Use sentence casing - see https://immutable.atlassian.net/wiki/spaces/PPS/pages/1937278619/Style+manual#id-%E2%9C%92%EF%B8%8F%F0%9F%93%84Stylemanual-Capitalizethefirstwordinasentenceandinheadings

2022-11-25 03:36 UTC, sprngbk commented on docs/main/tutorials/nft-checkout-primary-with-moonpay.md
> +Primary NFT checkout feature requires you to register with IMX as managed partner and build a commercial partnership with Moonpay.
At the beginning of this article, please provide:
* Brief description of what this "Moonpay NFT checkout" functionality is
* Description of what a "managed partner" is and why this is required for this feature
* Step by step instructions on how to do all the admin stuff required to use this feature (ie. become a "managed partner", setting up a commercial partnership with Moonpay, etc.)
* How setting up these endpoints fits into this "registration" process - and why is it required
* Also use an 'On this page' admonition box to link to the sections in this guide ([example](https://docs.x.immutable.com/docs/anatomy-smart-contract))

2022-11-25 03:36 UTC, sprngbk commented on docs/main/tutorials/nft-checkout-primary-with-moonpay.md
>  id: "nft-checkout-primary-with-moonpay"
I would say this isn't really a tutorial as it doesn't implement end-to-end functionality, it's more of a guide for a specific task. Let's put this under 'Advanced guides' in our docs.

2022-11-25 03:36 UTC, sprngbk commented on docs/main/tutorials/nft-checkout-primary-with-moonpay.md
> +# There are two steps to follow to complete registration with IMX platform:
Don't have this line as a header. It's best to have a summary of the steps, then link to them below.

Also just headline the steps with `1. ...` instead of `Step 1...`

2022-11-25 03:36 UTC, sprngbk commented on docs/main/tutorials/nft-checkout-primary-with-moonpay.md
> +* Triggering the mint: An endpoint to mint the asset, once payment has been confirmed with Moonpay.
Link to sections below

2022-11-25 03:36 UTC, sprngbk commented on docs/main/tutorials/nft-checkout-primary-with-moonpay.md
>  ```
```suggestion
```shell
```

2022-11-25 03:36 UTC, sprngbk commented on docs/main/tutorials/nft-checkout-primary-with-moonpay.md
>  - `seller_address` - Address on which Moonpay will transfer crypto
Put this into a table

2022-11-25 03:36 UTC, sprngbk commented on docs/main/tutorials/nft-checkout-primary-with-moonpay.md
> +### `IMX-Timestamp` (string) [refer](/docs/deep-dive-api-concepts/#imx-timestamp-string)
Don't have this as a header, just put the link next to the description of the params above

2022-11-25 03:36 UTC, sprngbk commented on docs/main/tutorials/nft-checkout-primary-with-moonpay.md
> +### `IMX-Signature` (string)
Link to this from the param description above, and label this "How to generate the `IMX-Signature`"

Also, don't have "(string)" in the header - you can specify its type underneath the header

2022-11-28 03:47 UTC, sprngbk requested changes

2022-11-28 03:47 UTC, sprngbk commented on docs/main/guides/advanced-guides/nft-checkout-primary-with-moonpay.md
> +</ListAdmonition>
Please use an ordered list

```suggestion
<ListAdmonition title="Steps:">
    <ol>
        <li><a href="#1-create-endpoints">Create required endpoints</a></li>
        <li><a href="#2-Register-with-IMX-platform-using-created-endpoints">Register with ImmutableX using created endpoints</a></li>
        <li><a href="#2-Validate-trigger-mint-request-is-sent-by-IMX">Validate that the trigger mint request is sent by ImmutableX</a></li>
   </ol>
</ListAdmonition>
```

2022-11-28 03:47 UTC, sprngbk commented on docs/main/guides/advanced-guides/nft-checkout-primary-with-moonpay.md
> +## 1: Create two endpoints
```suggestion
## 1. Create endpoints 
```

2022-11-28 03:47 UTC, sprngbk commented on docs/main/guides/advanced-guides/nft-checkout-primary-with-moonpay.md
> +* [Triggering the mint](#Triggering-the-mint-endpoint): An endpoint to mint the asset, once payment has been confirmed with Moonpay.
Number this list

2022-11-28 03:47 UTC, sprngbk commented on docs/main/guides/advanced-guides/nft-checkout-primary-with-moonpay.md
> +2. Build a commercial partnership with Moonpay, which can only be facilitated by your Partner Success Manager.
```suggestion
In order to use this feature, you need to complete the following:
1. Establish a commercial partnership with Moonpay (your partner success manager will facilitate this for you)
2. [Register with ImmutableX with the required endpoints](#how-to-set-up-and-register-endpoints)
```

2022-11-28 03:47 UTC, sprngbk commented on docs/main/guides/advanced-guides/nft-checkout-primary-with-moonpay.md
> +This tutorial provides a guide on how to set up endpoints required to register with IMX platform in order to access the [fiat NFT Checkout feature with Moonpay](https://docs.x.immutable.com/docs/link
```suggestion
## How to set up and register endpoints
```

2022-11-28 03:47 UTC, sprngbk commented on docs/main/guides/advanced-guides/nft-checkout-primary-with-moonpay.md
> +You are required to provide two endpoints for the Primary NFT Checkout with Moonpay before you can register with IMX platform:
```suggestion
You are required to provide the following endpoints:
```

2022-11-28 03:47 UTC, sprngbk commented on docs/main/guides/advanced-guides/nft-checkout-primary-with-moonpay.md
> +* [Triggering the mint](#Triggering-the-mint-endpoint): An endpoint to mint the asset, once payment has been confirmed with Moonpay.
```suggestion
1. [Trigger the mint](#Triggering-the-mint-endpoint): An endpoint to mint the asset once payment has been confirmed with Moonpay
2. [Get asset info](#Get-asset-info-endpoint): An endpoint to get information about the minted asset and render the checkout
```

2022-11-28 03:47 UTC, sprngbk commented on docs/main/guides/advanced-guides/nft-checkout-primary-with-moonpay.md
> +### Get asset info endpoint
Swap this section with the trigger mint section

2022-11-28 03:47 UTC, sprngbk commented on docs/main/guides/advanced-guides/nft-checkout-primary-with-moonpay.md
> +This endpoint will be used to trigger mint:
```suggestion
#### Headers required:
```

2022-11-28 03:47 UTC, sprngbk commented on docs/main/guides/advanced-guides/nft-checkout-primary-with-moonpay.md
> +
```suggestion

#### Request:
```

2022-11-28 03:47 UTC, sprngbk commented on docs/main/guides/advanced-guides/nft-checkout-primary-with-moonpay.md
> +
```suggestion

#### Response:
```

2022-11-28 03:47 UTC, sprngbk commented on docs/main/guides/advanced-guides/nft-checkout-primary-with-moonpay.md
> +            <td><a href="#How-to-generate-IMX-Signature">IMX Signature</a> header that should be validated</td>
This link doesn't go anywhere

2022-11-28 03:47 UTC, sprngbk commented on docs/main/guides/advanced-guides/nft-checkout-primary-with-moonpay.md
> +            <td>Timestamp header to validate IMX-Signature <a href="https://docs.x.immutable.com/docs/deep-dive-api-concepts/#imx-timestamp-string">refer</a></td>
* Use a relative link to the Markdown file.

2022-11-28 03:47 UTC, sprngbk commented on docs/main/guides/advanced-guides/nft-checkout-primary-with-moonpay.md
> +            <td><a href="#How-to-generate-IMX-Signature">IMX Signature</a> header that should be validated</td>
This isn't really descriptive. Can we please make the description clearer?

Also, append it with `([How to generate](#-insert-relative-markdown-link))`

2022-11-28 03:47 UTC, sprngbk commented on docs/main/guides/advanced-guides/nft-checkout-primary-with-moonpay.md
> +In order to register please reach out to your Partner Success Manager, who will put you in touch with Moonpay to facilitate a commercial partnership.
"Partner Success Manager" does not need to be capitalised - just "partner success manager" will do

2022-11-28 03:47 UTC, sprngbk commented on docs/main/guides/advanced-guides/nft-checkout-primary-with-moonpay.md
> +When these endpoints are complete, reach out to your Partner Success Manager to have these endpoints registered on IMX.
```suggestion
When you've set up the endpoints required in the previous step, reach out to your partner success manager to register them with ImmutableX.
```

2022-11-28 03:47 UTC, sprngbk commented on docs/main/guides/advanced-guides/nft-checkout-primary-with-moonpay.md
> +After registration IMX will send you a webhook key that will be used to validate the signature, when initiating the mint request.
Replace "IMX" with "ImmutableX" in all instances in this doc.

```suggestion
After registration, ImmutableX will send you a webhook key that will be used to validate the signature when initiating mint requests.
```

2022-11-28 03:47 UTC, sprngbk commented on docs/main/guides/advanced-guides/nft-checkout-primary-with-moonpay.md
> +## 3: Validate trigger mint request is sent by IMX
Can we please make this section clearer? What exactly is it doing and why?

2022-11-28 03:47 UTC, sprngbk commented on docs/main/tutorials/nft-checkout-primary-with-moonpay.md
> +Primary NFT checkout feature requires you to register with IMX as managed partner and build a commercial partnership with Moonpay.
Have these points been addressed?

2022-11-28 03:53 UTC, deepti-imx commented on docs/main/tutorials/nft-checkout-primary-with-moonpay.md
> +Primary NFT checkout feature requires you to register with IMX as managed partner and build a commercial partnership with Moonpay.
`Step by step instructions on how to do all the admin stuff required to use this feature (ie. become a "managed partner", setting up a commercial partnership with Moonpay, etc.)`
I added these as points at the top of the page. There's another document to-be-created by Jesse to address How to become Managed partner.

Have addressed rest of the 4 points.

2022-11-29 04:29 UTC, merged