[DX-1513] docs: Developer Hub changelog notes
immutable/imx-docs pull request #203
Opened 2022-12-13 02:23 UTC by CodeSchwert

## Description

Add Developer Hub breaking change notes to the changelog.

## Resolved issues

Jira: [DX-1513](https://immutable.atlassian.net/browse/DX-1513)

### Before submitting the PR, please consider the following:
- [x] It's beneficial if your pull request references an issue used to discuss the pull request ahead of time. If you haven't previously created an issue, please create one and discuss your contribution with the maintainers.
- [x] Prefix your PR title with `feat: `, `fix: `, `chore: `, `docs:`, or `refactor:`.
- [x] The description should clearly illustrate what problems the pull request solves.
- [x] Ensure that the commit messages follow our guidelines.
- [x] Resolve merge conflicts (if any).
- [x] Make sure that the current branch is up to date with the `main` branch.

### For internal Immutable developers:
- [ ] If you are adding or updating a documentation page, please also add or update the team ownership of that page (follow [this guide](https://immutable.atlassian.net/wiki/spaces/PPS/pages/1947927045/Docs+ownership+registry#What-to-do-when-adding%2Fupdating-documentation-pages%3F)).
- [ ] If you are adding or updating documentation for an SDK, please make sure that you meet the requirements in [this doc](https://immutable.atlassian.net/wiki/spaces/PPS/pages/1916994017/SDK+documentation+guide).
- [ ] Please obtain PR approval from all of the following:
    - Your tech lead (Fallback: Team lead or engineering manager)
    - Your product manager (Fallback: Group PM)
    - Another software engineer on your team

2022-12-13 03:12 UTC, ckailash requested changes
Suggested a change in wording

2022-12-13 11:38 UTC, ckailash approved these changes

2022-12-13 23:09 UTC, Nathan-Ballantyne approved these changes

2022-12-13 23:37 UTC, sprngbk commented on docs/main/troubleshooting/api/api-changelog.md
> +| 2022-12-16 |                      | - Release of [Immutable Developer Hub](https://hub.immutable.com).<br/>- The [Create Project API](https://docs.x.immutable.com/reference/#/operations/createProje
Do you think it's better to keep the HTML table format, might make it easier to read if multiple changes in a list format are added?

2022-12-19 07:10 UTC, suluvai approved these changes

2022-12-19 23:37 UTC, merged