docs: wt-551: add gamestop doc
immutable/imx-docs pull request #33
Opened 2022-07-12 07:11 UTC by ABashkirtseva

## Description

Add doc for gamestop

## Resolved issues
Jira: https://immutable.atlassian.net/browse/WT-551

### Before submitting the PR, please consider the follow:
- [x] It's beneficial if your pull request references an issue used to discuss the pull request ahead of time. If you haven't previously created an issue, please create one and discuss your contribution with the maintainers.
- [x] Prefix your PR title with `feat: `, `fix: `, `chore: `, `docs:`, or `refactor:`.
- [x] The description should clearly illustrate what problems the pull request solves.
- [x] Ensure that the commit messages follow our guidelines.
- [x] Resolve merge conflicts (if any).
- [x] Make sure that the current branch is up to date with the `main` branch.

2022-07-20 05:13 UTC, sprngbk requested changes
Thanks @ABashkirtseva! 

According to [this doc](https://immutable.atlassian.net/wiki/spaces/PPS/pages/1916994017/SDK+documentation+guide), you'll also need approval from:
* Your tech lead (Fallback: Team lead or engineering manager)
* Another engineer on your team
* Your product manager (Fallback: Group product manager)

Thanks!

2022-07-25 23:12 UTC, sprngbk approved these changes

2022-07-25 23:26 UTC, maksim-tsvetkov approved these changes

2022-07-26 03:05 UTC, edulino approved these changes

2022-07-29 01:02 UTC, merged