fix: SDK docs code flash
immutable/imx-docs pull request #61
Opened 2022-07-27 06:06 UTC by CodeSchwert

## Description

Fix the brief code flash when initially navigating to the SDK page.

## Resolved issues

Jira:

### Before submitting the PR, please consider the following:
- [ ] It's beneficial if your pull request references an issue used to discuss the pull request ahead of time. If you haven't previously created an issue, please create one and discuss your contribution with the maintainers.
- [x] Prefix your PR title with `feat: `, `fix: `, `chore: `, `docs:`, or `refactor:`.
- [x] The description should clearly illustrate what problems the pull request solves.
- [x] Ensure that the commit messages follow our guidelines.
- [x] Resolve merge conflicts (if any).
- [x] Make sure that the current branch is up to date with the `main` branch.

### For internal Immutable developers:
- [ ] If you are adding or updating documentation for an SDK, please make sure that you meet the requirements in [this doc](https://immutable.atlassian.net/wiki/spaces/PPS/pages/1916994017/SDK+documentation+guide).
- [ ] Please obtain PR approval from all of the following:
    - Your tech lead (Fallback: Team lead or engineering manager)
    - Your product manager (Fallback: Group PM)
    - Another software engineer on your team

2022-07-27 06:09 UTC, ckailash approved these changes

2022-07-27 06:11 UTC, matthewmuscat approved these changes

2022-07-27 06:11 UTC, matthewmuscat requested changes
It's still doing it actually

2022-07-27 06:19 UTC, ckailash commented
>

2022-07-28 04:46 UTC, CodeSchwert commented
@matthewmuscat there's a separate ticket for your sidebar loading issue: https://immutable.atlassian.net/browse/DX-1026. So I'll merge this to fix @ckailash's issue.

2022-07-28 04:46 UTC, merged