feat: Persist Survicate Ratings to cache
immutable/imx-docs pull request #70
Opened 2022-08-03 07:56 UTC by matthewmuscat

## Description
This PR ensures that ratings are persisted via local storage locally, so that it reflects the outcome of their previous rating. This also mitigates double-ups/spamming of rating submissions.

## Resolved issues
Jira: https://immutable.atlassian.net/browse/DX-990

### Before submitting the PR, please consider the following:
- [ ] It's beneficial if your pull request references an issue used to discuss the pull request ahead of time. If you haven't previously created an issue, please create one and discuss your contribution with the maintainers.
- [ ] Prefix your PR title with `feat: `, `fix: `, `chore: `, `docs:`, or `refactor:`.
- [ ] The description should clearly illustrate what problems the pull request solves.
- [ ] Ensure that the commit messages follow our guidelines.
- [ ] Resolve merge conflicts (if any).
- [ ] Make sure that the current branch is up to date with the `main` branch.

### For internal Immutable developers:
- [ ] If you are adding or updating documentation for an SDK, please make sure that you meet the requirements in [this doc](https://immutable.atlassian.net/wiki/spaces/PPS/pages/1916994017/SDK+documentation+guide).
- [ ] Please obtain PR approval from all of the following:
    - Your tech lead (Fallback: Team lead or engineering manager)
    - Your product manager (Fallback: Group PM)
    - Another software engineer on your team

2022-08-05 02:07 UTC, ckailash requested changes

2022-08-05 02:07 UTC, ckailash commented on src/components/SurvicateWidget/index.tsx
> +    const cachedRatings = JSON.parse(localStorage.getItem('sva_ratings'));
Is this a dictionary? Any reason why the data structure of choice is a dictionary instead of using the local storage as a key, value pair like so: key = hash(URL), value = rating?

2022-08-05 02:07 UTC, ckailash commented on src/components/SurvicateWidget/index.tsx
> +    log.find((rating: Rating) => rating.page === window.location.href);
If we used the key, value pair method defined above, you can avoid writing functions like `pageRating` with a `find` and directly look up the hashmap. Thoughts?

2022-08-05 02:07 UTC, ckailash commented on src/components/SurvicateWidget/index.tsx
> +      ];
With a key, value pair data structure, this logic is simplified as well.

2022-08-05 03:11 UTC, CodeSchwert reviewed
Think @ckailash suggestions make sense here unless there's a good reason to serialise JSON into local storage.

2022-08-09 00:51 UTC, matthewmuscat commented on src/components/SurvicateWidget/index.tsx
> +    const cachedRatings = JSON.parse(localStorage.getItem('sva_ratings'));
Yeah good point. Refactored here https://github.com/immutable/imx-docs/pull/70/commits/5352dda16d597eff2316a23196f1ea518858b0d4

2022-08-09 00:51 UTC, matthewmuscat commented on src/components/SurvicateWidget/index.tsx
> +    const cachedRatings = JSON.parse(localStorage.getItem('sva_ratings'));
Now it is:

```javascript
{
  "/sdk-docs/core-sdk-kotlin/installation": 4
  "/sdk-docs/core-sdk-kotlin/quickstart": 3
}
```

2022-08-09 03:10 UTC, CodeSchwert commented on src/components/SurvicateWidget/index.tsx
> +}
Maybe it's clearer to put the expected property names in here, like `formattedPathname`?

Also looks like only `formattedPathname` is used from the object stored in `localStorage`. Would it make more sense to just store the `formattedPathname` value not wrapped in an object?

2022-08-09 03:25 UTC, matthewmuscat commented on src/components/SurvicateWidget/index.tsx
> +}
> Maybe it's clearer to put the expected property names in here, like formattedPathname

```typescript
interface Rating {
  [key: string]: number;
}
``` 
dynamically represents this type such as `{ "route/to/page": 5 }`, 5 being the rating, e.g:
```javascript
{
  "/sdk-docs/core-sdk-kotlin/installation": 4
  "/sdk-docs/core-sdk-kotlin/quickstart": 3
}
```

Seeing as we will constantly be adding/editing pages, it wouldn't make sense to hardcode these routes.

> Would it make more sense to just store the formattedPathname value not wrapped in an object?

We need to store the ratings across every page in local storage. I chose to store ratings under one hashmap rather than every page as a separate local storage entry. I don't think there is a benefit to storing these individually tbh.

2022-08-09 03:39 UTC, CodeSchwert approved these changes

2022-08-09 03:50 UTC, merged