[DX-1062] Add API and SDK changelog
immutable/imx-docs pull request #74
Opened 2022-08-05 04:45 UTC by sprngbk

## Description

## Resolved issues
Jira: https://immutable.atlassian.net/browse/DX-1062

### Before submitting the PR, please consider the following:
- [ ] It's beneficial if your pull request references an issue used to discuss the pull request ahead of time. If you haven't previously created an issue, please create one and discuss your contribution with the maintainers.
- [ ] Prefix your PR title with `feat: `, `fix: `, `chore: `, `docs:`, or `refactor:`.
- [ ] The description should clearly illustrate what problems the pull request solves.
- [ ] Ensure that the commit messages follow our guidelines.
- [ ] Resolve merge conflicts (if any).
- [ ] Make sure that the current branch is up to date with the `main` branch.

### For internal Immutable developers:
- [ ] If you are adding or updating documentation for an SDK, please make sure that you meet the requirements in [this doc](https://immutable.atlassian.net/wiki/spaces/PPS/pages/1916994017/SDK+documentation+guide).
- [ ] Please obtain PR approval from all of the following:
    - Your tech lead (Fallback: Team lead or engineering manager)
    - Your product manager (Fallback: Group PM)
    - Another software engineer on your team

2022-08-05 05:10 UTC, ckailash approved these changes
LFG 🚀 :shipit:

2022-08-05 05:11 UTC, ckailash requested changes

2022-08-05 05:11 UTC, ckailash commented on src/pages/api-changelog.md
> +# API changelog
Could we add a sidebar? Ensure that this page's design matches the rest of the docs.

2022-08-05 05:20 UTC, ckailash commented on docusaurus.config.js
> +            type: 'dropdown',
The dropdown's design is a bit weird. Maybe some CSS changes are also required?

2022-08-09 01:13 UTC, sprngbk commented on src/pages/api-changelog.md
> +# API changelog
I've added it as a page in our docs so the sidebar issue is resolved 👍

2022-08-09 01:14 UTC, sprngbk commented on docusaurus.config.js
> +            type: 'dropdown',
Yup definitely, am on it 👍

2022-08-09 03:36 UTC, matthewmuscat approved these changes
LGTM!

2022-09-09 06:04 UTC, closed without merging