docs/feat: Add SDK page info, add wallet SDK button category
immutable/imx-docs pull request #86
Opened 2022-08-14 03:34 UTC by sprngbk

## Description

This PRL
* Updates the SDKs page with info on SDKs and how they can be used together
* Adds a category for wallet SDKs
  <img width="671" alt="image" src="https://user-images.githubusercontent.com/96668470/184521271-4bab8ea9-3b2b-4485-8bd8-4465dfb7fd55.png">

## Resolved issues
Jira: N/A

### Before submitting the PR, please consider the following:
- [ ] It's beneficial if your pull request references an issue used to discuss the pull request ahead of time. If you haven't previously created an issue, please create one and discuss your contribution with the maintainers.
- [ ] Prefix your PR title with `feat: `, `fix: `, `chore: `, `docs:`, or `refactor:`.
- [ ] The description should clearly illustrate what problems the pull request solves.
- [ ] Ensure that the commit messages follow our guidelines.
- [ ] Resolve merge conflicts (if any).
- [ ] Make sure that the current branch is up to date with the `main` branch.

### For internal Immutable developers:
- [ ] If you are adding or updating a documentation page, please also add or update the team ownership of that page (follow [this guide](https://immutable.atlassian.net/wiki/spaces/PPS/pages/1947927045/Docs+ownership+registry#What-to-do-when-adding%2Fupdating-documentation-pages%3F)).
- [ ] If you are adding or updating documentation for an SDK, please make sure that you meet the requirements in [this doc](https://immutable.atlassian.net/wiki/spaces/PPS/pages/1916994017/SDK+documentation+guide).
- [ ] Please obtain PR approval from all of the following:
    - Your tech lead (Fallback: Team lead or engineering manager)
    - Your product manager (Fallback: Group PM)
    - Another software engineer on your team

2022-08-15 03:40 UTC, RenatoChitolina approved these changes

2022-08-17 01:10 UTC, matthewmuscat requested changes

2022-08-17 01:10 UTC, matthewmuscat commented on docs/main/sdks.mdx
> +<SdkButtonList sdks={linkSDK} sdks={linkSDK} />
Duplicate props?
```suggestion
<SdkButtonList sdks={linkSDK} />
```

2022-08-17 01:10 UTC, matthewmuscat commented on src/components/SdkSwitcher/index.tsx
> +    (sdk: { url: string }) => sdk.url == history.location.pathname
Can you just `url == history.location.pathname` here as you've destructured `url`?

2022-08-17 01:19 UTC, sprngbk commented on src/components/SdkSwitcher/index.tsx
> +    (sdk: { url: string }) => sdk.url == history.location.pathname
Oh oops, it's not destructured. It's just specifying the type for `sdk`. I think I'll leave it un-destructured for clarity?

2022-08-17 01:22 UTC, matthewmuscat approved these changes

2022-08-17 01:30 UTC, merged

2022-08-17 02:15 UTC, CodeSchwert commented on src/components/SdkSwitcher/index.tsx
>      localStorage.setItem(SdkIdKey, sdkItem.id.toString());
✅